In [6]:
import pandas as pd
import numpy as n

cleaning the data - convert fields names and values into lowercase and replace spaces with underscore sign

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

In [8]:
df.columns = df.columns.str.lower().str.replace(' ','_')
df.head()

,laptop,status,brand,model,cpu,ram,storage,storage_type,gpu,screen,touch,final_price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

In [9]:
TextFields = list(df.dtypes[df.dtypes == 'object'].index)
for s in TextFields:
    df[s] = df[s].str.lower().str.replace(' ','_')
df.head()

,laptop,status,brand,model,cpu,ram,storage,storage_type,gpu,screen,touch,final_price
0,asus_expertbook_b1_b1502cba-ej0436x_intel_core...,new,asus,expertbook,intel_core_i5,8,512,ssd,NaN,15.6,no,1009.00
1,alurin_go_start_intel_celeron_n4020/8gb/256gb_...,new,alurin,go,intel_celeron,8,256,ssd,NaN,15.6,no,299.00
2,asus_expertbook_b1_b1502cba-ej0424x_intel_core...,new,asus,expertbook,intel_core_i3,8,256,ssd,NaN,15.6,no,789.00
3,msi_katana_gf66_12uc-082xes_intel_core_i7-1270...,new,msi,katana,intel_core_i7,16,1000,ssd,rtx_3050,15.6,no,1199.00
4,hp_15s-fq5085ns_intel_core_i5-1235u/16gb/512gb...,new,hp,15s,intel_core_i5,16,512,ssd,NaN,15.6,no,669.01

Exploratory data analysis

In [10]:
Total_datasets=len(df)
Testing_Dataset_count=int(0.2*Total_datasets)
Validation_Dataset_Count=int(0.2*Total_datasets)
Train_Dataset_Count = Total_datasets - Testing_Dataset_count-Validation_Dataset_Count
Total_datasets,Testing_Dataset_count,Validation_Dataset_Count,Train_Dataset_Count

(2160, 432, 432, 1296)

logarithmic value of msrp - is done to avoid long tail distribution and make it normal distribution(bell curve)

In [11]:
n.log([1+1,10+1,100+1,1000+1])

array([0.69314718, 2.39789527, 4.61512052, 6.90875478])

Make sure the column values are not NULL(empty)

In [16]:
df.isnull().sum()
df['final_price'].skew()

np.float64(1.6495877663192549)

Validation framework 60% Trainingmodel, 20% model validation,20% testing the model

In [13]:
Dataframe_count = len(df)
Validation_data_count=int(0.2*Dataframe_count)
Testing_data_count=int(0.2*Dataframe_count)
Train_data_count=Dataframe_count- Validation_data_count - Testing_data_count
Dataframe_count ,Validation_data_count,Testing_data_count,Train_data_count

(2160, 432, 432, 1296)

In [14]:
Validation_dataframe=df.iloc[0:Validation_data_count]
Validation_dataframe
Testing_dataframe =df.iloc[Validation_data_count:Validation_data_count+Testing_data_count]
Testing_dataframe
Training_dataframe=df.iloc[Validation_data_count+Testing_data_count:]
Training_dataframe

,laptop,status,brand,model,cpu,ram,storage,storage_type,gpu,screen,touch,final_price
864,asus_rog_strix_g17_g713qr-k4189_amd_ryzen_7_58...,new,asus,rog,amd_ryzen_7,32,1000,ssd,rtx_3070,17.3,no,2649.44
865,asus_zenbook_14_ux3402za-kp490w_intel_core_i5-...,new,asus,zenbook,intel_core_i5,16,512,ssd,NaN,14.0,no,846.31
866,hp_15s-fq2180ns_intel_core_i3-1115g4/8gb/512gb...,new,hp,15s,intel_core_i3,8,512,ssd,NaN,15.6,no,414.84
867,hp_250_g9_intel_core_i3-1215u/8gb/256_gb_ssd/1...,new,hp,250,intel_core_i3,8,256,ssd,NaN,15.6,no,399.37
868,lenovo_thinkbook_15_g2_itl_intel_core_i5-1135g...,new,lenovo,thinkbook,intel_core_i5,16,512,ssd,NaN,15.6,no,1069.00
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,razer_blade_17_fhd_360hz_intel_core_i7-11800h/...,refurbished,razer,blade,intel_core_i7,16,1000,ssd,rtx_3060,17.3,no,2699.99
2156,razer_blade_17_fhd_360hz_intel_core_i7-11800h/...,refurbished,razer,blade,intel_core_i7,16,1000,ssd,rtx_3070,17.3,no,2899.99
2157,razer_blade_17_fhd_360hz_intel_core_i7-11800h/...,refurbished,razer,blade,intel_core_i7,32,1000,ssd,rtx_3080,17.3,no,3399.99
2158,razer_book_13_intel_evo_core_i7-1165g7/16gb/1t...,refurbished,razer,book,intel_evo_core_i7,16,1000,ssd,NaN,13.4,yes,1899.99
2159,razer_book_fhd+_intel_evo_core_i7-1165g7/16gb/...,refurbished,razer,book,intel_evo_core_i7,16,256,ssd,NaN,13.4,yes,1699.99

In [15]:
base = ['ram','storage','final_price','screen']
df=df[base]
df['ram'].median()


index=n.arange(Total_datasets)
n.random.seed(42)
n.random.shuffle(index)
df_train = df.iloc[index[:Train_Dataset_Count]]
df_train =df_train.reset_index(drop=True)
df_val=df.iloc[index[Train_Dataset_Count:Train_Dataset_Count+Validation_Dataset_Count]]
df_val=df_val.reset_index(drop=True)
df_test=df.iloc[index[Train_Dataset_Count+Validation_Dataset_Count:]]
df_test =df_test.reset_index(drop=True)
y_train=n.log1p(df_train.final_price.values)
y_val=n.log1p(df_val.final_price.values)
y_test=n.log1p(df_test.final_price.values)
del df_train['final_price']
del df_val['final_price']
del df_test['final_price']